include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unused_element_parameter: ignore
    not_enough_positional_arguments: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    require_trailing_commas: false
    unnecessary_raw_strings: false
    sort_pub_dependencies: false
